  version: '3'

  includes:
    plugins: "plugins/Taskfile.yml"
    internal: "internal.yml"

  tasks:
    build:
      cmds:
        - task: plugins:build

    build:plugins:
      cmds:
        - go build -buildmode=plugin -o target/redpanda-benthos_io_darwin_arm64.so ./plugins/redpanda-benthos/io/io.go
